# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api.proto for package 'api'
# Original file comments:
#
# Copyright (C) 2017 Dgraph Labs, Inc. and Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Style guide for Protocol Buffer 3.
# Use CamelCase (with an initial capital) for message names – for example,
# SongServerRequest. Use underscore_separated_names for field names – for
# example, song_name.
#

require 'grpc'
require_relative 'api_pb'

module Api
  module Dgraph
    # Graph response.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'api.Dgraph'

      rpc :Login, LoginRequest, Response
      rpc :Query, Request, Response
      rpc :Alter, Operation, Payload
      rpc :CommitOrAbort, TxnContext, TxnContext
      rpc :CheckVersion, Check, Version
    end

    Stub = Service.rpc_stub_class
  end
end
